name: pda_scanner_next
description: This is a scanning plug-in for PDA to Listen for scanned events and get results.
version: 0.1.4
author: andy <360475097@qq.com>
homepage: https://github.com/m430/pda_scanner

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.andy.pda_scanner
    pluginClass: PdaScannerPlugin